apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
    remote_write:
      - url: "http://prometheus-service.monitor.svc.cluster.local:9090/api/v1/write"

        write_relabel_configs:
          # drop specific metrics from remote-write
        - source_labels: ['__name__']
          regex: 'go_gc_.*'
          action: 'drop'
      
          # keep only specific labels for the kept metrics
        - regex: '__name__|instance|job|version|branch'
          action: 'labelkeep'
      
        - action: 'replace'
          target_label: 'source'
          replacement: 'writer-prometheus'